# Generated by Django 5.2.5 on 2025-11-02 08:51

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated if left blank.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10)),
                ('summary', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('header_image_desktop', models.ImageField(upload_to='blog_headers/desktop/')),
                ('header_image_mobile', models.ImageField(upload_to='blog_headers/mobile/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=255)),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='clientele_logos/')),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated if left blank.', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10)),
                ('header_image_desktop', models.ImageField(upload_to='project_headers/desktop/')),
                ('header_image_mobile', models.ImageField(upload_to='project_headers/mobile/')),
                ('brief_description', models.TextField()),
                ('detail_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_featured_home', models.BooleanField(db_index=True, default=False)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(max_length=150)),
                ('author_image', models.ImageField(upload_to='testimonial_authors/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='mainapp.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified', models.BooleanField(default=False, help_text='Indicates if admin notification has been sent.')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_info', models.CharField(blank=True, help_text='User-Agent string or similar device identifier.', max_length=512)),
                ('service_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.servicecategory')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_hit', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Daily Hit Count',
                'verbose_name_plural': 'Daily Hit Counts',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='mainapp.project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
