# Generated by Django 6.0 on 2025-12-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactsubmission",
            name="device_info",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="notified",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="service_inquiry",
        ),
    ]
