# Generated by Django 5.2.5 on 2025-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_contactsubmission_device_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('scope', models.CharField(max_length=300, verbose_name='Scope')),
                ('tech_used', models.CharField(max_length=200, verbose_name='Tech Used')),
                ('performance_impact', models.CharField(max_length=200, verbose_name='Performance Impact')),
                ('background_image', models.ImageField(upload_to='project_home_banners/', verbose_name='Background Image')),
                ('cement_eliminated', models.CharField(max_length=50, verbose_name='Cement Eliminated')),
                ('water_saved', models.CharField(max_length=50, verbose_name='Water Saved')),
            ],
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
