# Generated by Django 5.2.5 on 2025-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_projecthomebanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=75, verbose_name='Customer Name')),
                ('customer_designation', models.CharField(max_length=75, verbose_name='Customer Designation')),
                ('customer_image', models.ImageField(upload_to='homepage_testimonials/', verbose_name='Customer Image')),
                ('testimonial', models.TextField(max_length=300, verbose_name='Testimonial')),
            ],
        ),
    ]
