# Generated by Django 5.2.5 on 2025-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_homepagetestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='testimonial_authors/'),
        ),
    ]
