# Generated by Django 5.2.5 on 2025-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_testimonial_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetestimonial',
            name='customer_image',
            field=models.ImageField(blank=True, upload_to='homepage_testimonials/', verbose_name='Customer Image'),
        ),
    ]
