# Generated by Django 5.2.5 on 2025-12-28 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_homepagetestimonial_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthomebanner',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='feature_on_project_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projecthomebanner',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_banners', to='mainapp.project'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
