# Generated by Django 5.2.5 on 2025-12-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_projecthomebanner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='header_image_desktop',
        ),
        migrations.RemoveField(
            model_name='project',
            name='header_image_mobile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured_home',
        ),
    ]
