# Generated by Django 5.2.5 on 2025-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_project_header_image_desktop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('photo', models.ImageField(upload_to='leadership_photos/')),
            ],
        ),
    ]
