# Generated by Django 5.2.5 on 2025-12-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
