# Generated by Django 5.2.8 on 2026-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_alter_leadership_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("publisher_name", models.CharField(max_length=100)),
                (
                    "publisher_logo",
                    models.ImageField(upload_to="media_coverage_logos/"),
                ),
                ("publish_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PR", "Press Release"),
                            ("INTERVIEW", "Interview / Authored Article"),
                        ],
                        max_length=20,
                    ),
                ),
                ("show_on_homepage", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Media Coverage",
                "ordering": ["-publish_date"],
            },
        ),
    ]
